### PR TITLE
Track 5, along with QOL changes

### PR DESCRIPTION
**Pull request by ThatZeoMan**
- Track 5 fully-functional!
- moved flash event to VFX
- combined many "background options" events into just 1 per minigame
- added 3 new values to the file type, colorD, colorE, and colorF. It's a band-aid fix, but i am not about to rewrite the whole parsing stuff
- all changed events have backwards-compatibility with older files
- unified game titles, specifically [WIP]
- other minor changes

### CODE REVIEW

**Comment by minenice55** [comment]
should be marked as a draft if additional track is being worked on

**Comment by ThatZeoMan** [comment]
its ready!

**Comment by ThatZeoMan** [comment]
HALT!
It has come to my attention that the new flash in vfx does not work! Please do not merge this yet!

**Comment by ThatZeoMan** [comment]
UNHALT!
Flashes now work properly. Enjoy your 5th track!

**Pull request merged**
