### PR TITLE
Dog Ninja

### PR DESCRIPTION
**Pull request by AstrlJelly**
during making dog ninja, i got a lot more experience, so i went back in double date and fixed some of my old code (VERY BAD CODE). basically, all it does is schedule inputs and get rid of the weird animations; should i make a separate branch for these changes/not include them in this PR?

TODO:
* fix bezier curves (they still look janky)
* add more objects/sprites and sfx for the objects
* finish slice animations and set up the logic for which animation to use (ev might be doing these)
 - left, right, and middle need to be done.
* make halves exist

LESS PRIORITIZED:
* add barely stuff
 - shouldn't be too hard, just make the object fall quickly with spin(?) and make a little dust cloud
* upscaled textures
 - of course i would LOVE for this to be in the main todo but merging doesn't require them, and ev 

CONSIDERING:
* add a prefunction to call the throw cue early
 - could add another use case for dog ninja
* add prepare animation (EV IF YOU'RE DOING ANIMS PLS DO THIS)
 - maybe also hold and release B to slice akin to swiping?

(sorry if i get anything wrong, still learning github :/ )

### CODE REVIEW

**Comment by blank3times** [comment]
What is prefunction mean? :)

**Comment by minenice55** [comment]
the double date minigame is a separate feature and it is best if it were in its own PR

**Comment by AstrlJelly** [comment]
> What is prefunction mean? :)

in my case, it means you can place a block before the game has been loaded (i.e dj school, fan club, pajama party) and it will still actually throw the object, unlike games like karate man. though, if it's too complicated for me to handle now, i might tackle it later.

**Comment by blank3times** [comment]
> > What is prefunction mean? :)
> 
> in my case, it means you can place a block before the game has been loaded (i.e dj school, fan club, pajama party) and it will still actually throw the object, unlike games like karate man. though, if it's too complicated for me to handle now, i might tackle it later.

Oh this! I love these, they're super useful for cool things like remix 9 sorts of stuff.

**Comment by AstrlJelly** [comment]
i renamed my branch, gotta make a new pr

**Pull request closed without merging**
