### PR TITLE
Octopus Machine Initialization 

### PR DESCRIPTION
**Pull request by GhostlyGuyGD**
Octopus Machine Stuff I suppose.

Contains:
Bop Action
3 Octopuses 
and a thing that points to your Octopus.

### CODE REVIEW

**Comment by minenice55** [comment]
will wait for more game functionality before merging

**Comment by GhostlyGuyGD** [comment]
Alright, I'll start working more on it. 👍

**Comment by 3ndgamer28** [comment]
holy crap

**Comment by GhostlyGuyGD** [comment]
I'm hoping I didn't screw up here. I have added 3 different types of Bopping into Octopus Machine.

**Comment by GhostlyGuyGD** [comment]
Synced it as well with the recent Ringside addition thingy.

**Pull request closed without merging**
