### PR TITLE
[DRAFT] Tunnel

### PR DESCRIPTION
**Pull request by DPS2004**

### CODE REVIEW

**Comment by minenice55** [comment]
will look at this once I settle out the new minigame definition schema, may also use this to test out arbitrarily named parameters

**Comment by DPS2004** [comment]
sounds good, let me know if I need to do anything

**Comment by ThatZeoMan** [comment]
this is where it all began

**Comment by ThatZeoMan** [comment]
image

**Comment by DPS2004** [comment]
tunnel :(

**Comment by fancythedeveloper** [comment]
> image

i wish i understood this

**Pull request merged**
